name: Lint

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  statuses: write

jobs:
  lint:
    name: Lint
    uses: theholocron/.github/.github/workflows/lint.yml@main
    secrets: inherit
    with:
      enable-auto-commit: true
